### ISSUE TITLE
Encountered issue while trying to export sqlite3.

### ISSUE THREAD

**Issue by nan2xiao** [JacobLinCool/d1-manager#60]
The program can run normally, manage, view, and use AI, and can also export to CSV,
but it cannot export to sqlite3.

![image](https://github.com/JacobLinCool/d1-manager/assets/159799757/7bfa0ee0-17b0-4972-9619-a8f233631b80)

![image](https://github.com/JacobLinCool/d1-manager/assets/159799757/24a3c073-c97a-4087-8bfc-735eb3d3bd75)

**Comment by grrowl** [comment]
Here's the error, although not super helpful, when I try to Download

```
d1-manager:server-error Error: D1_DUMP_ERROR: Status + 400
    at D1DatabaseSessionAlwaysPrimary.dump (cloudflare-internal:d1-api:234:23)
    at async GET5 (functionsWorker-0.6134034288967083.js:19255:20)
    at async render_endpoint (functionsWorker-0.6134034288967083.js:19825:20)
    at async resolve2 (functionsWorker-0.6134034288967083.js:23146:22)
    at async Object.handle (functionsWorker-0.6134034288967083.js:5223:22)
    at async respond (functionsWorker-0.6134034288967083.js:23040:22)
    at async Object.fetch (functionsWorker-0.6134034288967083.js:23515:13) +0ms
```
